### PR TITLE
fix(props): fix props module

### LINKED ISSUE #31: Crash with svg elements
When updateElement is called on an svg element it crashes when trying to remove the previous classes:

```
Uncaught TypeError: node.className.split is not a function
    at updateElement (updateElement.js:7)
    at patchVNode (patchVNode.js:8)
    at updateChildren (updateChildren.js:25)
    at patchVNodeChildren (patchVNodeChildren.js:11)
    at patchVNode (patchVNode.js:15)
    at patch (init.js:27)
```

### PR DESCRIPTION
**Pull request by TylorS**
Fixes #31

### CODE REVIEW

File: src/modules/props.ts [hunk 1]
```diff
@@ -48,10 +51,26 @@ function updateProps(formerVNode: ElementVNode, vNode: ElementVNode): void {
   props = props || {}
 
   for (const key in formerProps)
-    if (PROPERTIES_TO_SKIP.indexOf(key) === -1 && !props[key])
+    if (!PROPERTIES_TO_SKIP[key] && !props[key]) {
```
Comment (Frikki) [inline src/modules/props.ts]: Nested if-statements are considered poor coding style and lead to convoluted and hard-to-understand code. Below is my suggestion on how to fix them. Consider using other names for the variables if you find it so.

```
const propertyIsMissing = !PROPERTIES_TO_SKIP[key] && !props[key]
const keyIsClassName = propertyIsMissing && key === 'className'
const shouldRemoveAttribute = propertyIsMissing && ATTRIBUTE_TO_REMOVE[key]

if (keyIsClassName)
  removePreviousClassName(formerProps[key], element)

if (shouldRemoveAttribute)
  element.removeAttribute(key)

if (propertyIsMissing)
  delete element[key]
```

File: src/modules/props.ts [hunk 2]
```diff
@@ -48,10 +51,26 @@ function updateProps(formerVNode: ElementVNode, vNode: ElementVNode): void {
...
+    }
 
-  for (const key in props)
-    if (PROPERTIES_TO_SKIP.indexOf(key) === -1)
-      element[key] = props[key]
+  for (const key in props) if (!PROPERTIES_TO_SKIP[key]) element[key] = props[key]
+}
+
+function removePreviousClassName(className: string, element: Element) {
+  if (className && element.classList) {
```
Comment (Frikki) [inline src/modules/props.ts]: Same as above.

```
const shouldRemoveClassName = className && element.classList
const shouldRemoveClassAttribute = shouldRemoveClassName && element.getAttribute('class') === ´''

if (shouldRemoveClassName)
  element.classList.remove(...className.split(' '))

if (shouldRemoveClassAttribute)
  element.removeAttribute('class')
```

File: src/patchVNode/updateElement.ts [hunk 3]
```diff
@@ -6,12 +6,6 @@ export function updateElement(formerVNode: VNode, vNode: VNode): ElementVNode {
   if (isElement(node)) {
```
Comment (Frikki) [inline src/patchVNode/updateElement.ts:6]: Again, consider using the same technique as above to eliminate nested if-statements.

**Review by Frikki — CHANGES_REQUESTED** [review]
Fix nested if-statements to make the code more readable, less convoluted, and easier to maintain.

File: src/patchVNode/updateElement.ts (hunk 3 above)
Comment (TylorS) [reply src/patchVNode/updateElement.ts:6]: This type guard is required by TypeScript to be here like this because of the `node is Element` check must be performed in the `if`.

image

Comment (Frikki) [reply src/patchVNode/updateElement.ts:6]: Okay.

**Review by Frikki — APPROVED** [review]
